import = ["/home/hanu58/.config/alacritty/gruvbox_material_hard_dark.toml"]

[env]
TERM = "xterm-256color"

[window]
padding.x = 8
padding.y = 8

decorations = "Buttonless"

[font]
size = 13

builtin_box_drawing = true

#normal = { family = "JetBrainsMono NF", style = "Regular" }
#bold = { family = "JetBrainsMono NF", style = "Bold" }
#italic = { family = "JetBrainsMono NF", style = "Italic" }
#bold_italic = { family = "JetBrainsMono NF", style = "Bold Italic" }
